#!/bin/sh
#
# Simple Redis init.d script conceived to work on Linux systems
# as it does use of the /proc filesystem.

REDISPORT=6385
EXEC=/usr/local/Redis-3.2.1-cluster/redis-${REDISPORT}/bin/redis-server
CLIEXEC=/usr/local/Redis-3.2.1-cluster/redis-${REDISPORT}/bin/redis-cli

PIDFILE=/var/run/redis_${REDISPORT}.pid
CONF="/usr/local/Redis-3.2.1-cluster/redis-${REDISPORT}/conf/${REDISPORT}.conf"

case "$1" in
    start)
        if [ -f $PIDFILE ]
        then
                echo "$PIDFILE exists, process is already running or crashed"
        else
                echo "Starting Redis server..."
                $EXEC $CONF
        fi
        ;;
    stop)
        if [ ! -f $PIDFILE ]
        then
                echo "$PIDFILE does not exist, process is not running"
        else
                PID=$(cat $PIDFILE)
  		kill -9 $PID
                rm -rf $PIDFILE
		sleep 1 
                echo "Stopping ..."
                #$CLIEXEC -p $REDISPORT shutdown
                #while [ -x /proc/${PID} ]
                #do
                #    echo "Waiting for Redis to shutdown ..."
                #   sleep 1
                #done
                #echo "Redis stopped"
        fi
        ;;
    *)
        echo "Please use start or stop as first argument"
        ;;
esac
